/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffddb8',
        'surface-container-lowest': '#010f1f',
        'on-secondary-fixed-variant': '#653e00',
        'on-primary-fixed-variant': '#783200',
        'on-secondary': '#472a00',
        'on-tertiary': '#003824',
        'surface-variant': '#273647',
        'secondary-container': '#ee9800',
        'surface-container': '#122131',
        'secondary-fixed-dim': '#ffb95f',
        'surface-container-highest': '#273647',
        'error-container': '#93000a',
        'primary-fixed': '#ffdbca',
        'on-secondary-fixed': '#2a1700',
        'on-background': '#d4e4fa',
        'on-surface': '#d4e4fa',
        primary: '#ffb690',
        'tertiary-container': '#00b07a',
        surface: '#051424',
        'on-surface-variant': '#e0c0b1',
        'surface-bright': '#2c3a4c',
        tertiary: '#4edea3',
        background: '#051424',
        'on-error-container': '#ffdad6',
        'surface-dim': '#051424',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#002113',
        'on-secondary-container': '#5b3800',
        outline: '#a78b7d',
        'on-error': '#690005',
        error: '#ffb4ab',
        'primary-fixed-dim': '#ffb690',
        'on-primary': '#552100',
        'primary-container': '#f97316',
        'surface-container-low': '#0d1c2d',
        secondary: '#ffb95f',
        'inverse-surface': '#d4e4fa',
        'outline-variant': '#584237',
        'tertiary-fixed-dim': '#4edea3',
        'surface-tint': '#ffb690',
        'inverse-on-surface': '#233143',
        'on-primary-container': '#582200',
        'on-tertiary-container': '#003b26',
        'surface-container-high': '#1c2b3c',
        'on-primary-fixed': '#341100',
        'inverse-primary': '#9d4300',
        'tertiary-fixed': '#6ffbbe',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-desktop': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        gutter: '1rem',
        margin: '1rem',
        'space-2xl': '4rem',
        'space-lg': '1.5rem',
        'margin-desktop': '2rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'display-lg': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
        'body-lg': ['Space Grotesk'],
        'label-md': ['JetBrains Mono'],
        'headline-lg-mobile': ['Space Grotesk'],
        'display-lg-mobile': ['Space Grotesk'],
        'label-lg': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
        'body-sm': ['Space Grotesk'],
        'title-md': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'telemetry-num': ['JetBrains Mono'],
        'body-md': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'telemetry-num': ['22px', { lineHeight: '26px', letterSpacing: '0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
